#+TITLE: Typeclasses

[[file:README.org][Back to Prelude]]

* Notes
+ Typeclasses allow us to generalize over a set of types
  in order to define and execute a standard set of features
  for those types.
  + For example, the ability to test values for equality.
    We can test any data of a type that implements the typeclass
    known as "Eq" for equality.

#+BEGIN_SRC haskell
Prelude> :info Bool
data Bool = False | True
instance Bounded Bool
instance Enum Bool
instance Eq Bool
instance Ord Bool
instance Read Bool
instance Show Bool
#+END_SRC

+ The information includes the data declaration for Bool and
  which typeclasses it already has instances of.
  1. ~instance Bounded Bool~ for types that have an upper and lower
     bound
  2. ~instance Enum Bool~ for things that can be enumerated
  3. ~instance Eq Bool~ for things that can be tested for equality
  4. ~instance Ord Bool~ for things that can be put into a sequential order
  5. ~instance Read Bool~ parses strings into other types
     + Book says not to use it apparently
  6. ~instance Show Bool~ renders things into strings

+ Typeclasses have a hierarchy of sorts
  + All ~Fractional~ numbers implement the ~Num~ typeclass,
    but not all ~Num~ are ~Fractional~ as an example.
  + All members of ~Ord~ are members of ~Eq~, and all members
    of ~Enum~ are members of ~Ord~

#+BEGIN_SRC haskell
Prelude> :info Eq
class Eq a where
  (==) :: a -> a -> Bool
  (/=) :: a -> a -> Bool

instance Eq a => Eq [a]
instance Eq Ordering
instance Eq Int
instance Eq Float
instance Eq Double
instance Eq Char
instance Eq Bool
instance (Eq a, Eq b) => Eq (a, b)
instance Eq ()
instance Eq a => Eq (Maybe a)
instance Eq Integer
#+END_SRC

+ First it tells we have a typeclass called ~Eq~ that have two
  functions, ~==~ and ~/=~ ("equal to" and "not equal to")
  + Both operators take two type variables that have an instance
    of ~Eq~ and return a ~Bool~
+ Then it lists what types are instances of ~Eq~

#+BEGIN_SRC haskell
data (,) a b = (,) a b
instance (Eq a, Eq b) => Eq (a, b)
instance (Ord a, Ord b) => Ord (a, b)
instance (Read a, Read b) => Read (a, b)
instance (Show a, Show b) => Show (a, b)
#+END_SRC

+ This tells us the equality of two tuples (a, b) depends on the
  equality of their constituent values.
  + which is why ~(1, 'a') == (2, 'b')~ works
    but ~(1, 2) == ('a', 'b')~ doesn't
    + basically alpha equivalence

#+BEGIN_SRC haskell
data Trivial = Trivial
#+END_SRC

+ With no ~deriving~ clause on this type declaration, there is no
  typeclass instance of any kind.
+ If we run ~Trivial == Trivial~, it will give a type error complaining
  about no instance for (Eq Trivial) arising from the use of ~==~
+ This should fix it

  #+BEGIN_SRC haskell
data Trivial = Trivial' -- Data constructors don't need the same name

instance Eq Trivial where
  Trivial' == Trivial' = True
  #+END_SRC

+ ~instance~ begins a declaration for a typeclass instance, which is
  how equality, stringification, orderability, enumeration, or other typeclasses
  should work for a particular datatype.
+ The first name after ~instance~ is the typeclass the instance is providing.
  + In this case ~Eq~
+ The next is the type the instance is being provided for.
  + which is ~Trivial~ in this case
+ ~where~ ends the declaration and beginning of the instance. What follows
  are the functions being implemented.
+ ~Trivial'~ is the first/left argument to the ~==~ function, followed by another
  ~Trivial'~ as the second/right argument, then the result of the code is
  declared to evaluate to True

#+BEGIN_SRC haskell
data DayOfWeek =
  Mon | Tue | Weds | Thu | Fri | Sat | Sun

data Date =
  Date DayOfWeek Int
#+END_SRC

+ Can't do anything with this yet since there are no operations defined for them...
  yet

#+BEGIN_SRC haskell
instance Eq DayOfWeek where
  (==) Mon Mon = True
  (==) Tue Tue = True
  (==) Weds Weds = True
  (==) Thu Thu = True
  (==) Fri Fri = True
  (==) Sat Sat = True
  (==) Sun Sun = True
  (==) _ _ = False
#+END_SRC

+ This is obviously just to see if two given days are the same, else false.
  Now to write an ~Eq~ instance for type ~Date~

#+BEGIN_SRC haskell
instance Eq Date where
  (==) (Date weekday dayOfMonth)
       (Date weekday' dayOfMonth') =
    weekday == weekday'
    && dayOfMonth == dayOfMonth'
#+END_SRC

+ Test if it works

#+BEGIN_SRC haskell
Prelude> Date Thu 10 == Date Thu 10
True
Prelude> Date Thu 10 == Date Thu 11
False
Prelude> Date Thu 10 == Date Weds 10
False
#+END_SRC

+ It works, also we can't print them in the REPL yet since there is no
  ~Show~ instance.

+ Partial application /= partial function.
  + A partial function is one that doesn't handle all the possible cases.
    + Partial functions bad
+ If we were to take our ~DayOfWeek~ code without ~(==) _ _ = False~
  and have it compare two different values
  (i.e. ~Mon == Tue~) we would get this

#+BEGIN_SRC haskell
Prelude> Mon == Tue
\*** Exception: code/derivingInstances.hs:
(19,3)-(25,23):
Non-exhaustive patterns in function ==
#+END_SRC

+ The ~_~ is important since it provides a fallback case, or an "else" condition
  like in imperative languages. Without it pattern matching becomes non-exhaustive.
+ Another example of using this fallback mechanism

#+BEGIN_SRC haskell
f :: Int -> Bool
f 1 = True
f 2 = True
f 3 = True
f _ = False
#+END_SRC

+ We sometimes need to require our argument(s) to provide some typeclass
  instances for us in order to write an instance for the datatype containing them
  when we're writing an instance of a typeclass for something with polymorphic
  parameters

#+BEGIN_SRC haskell
data Identity a =
  Identity a

instance Eq (Identity a) where
  (==) (Identity v) (Identity v') = v == v'
#+END_SRC

+ What we want is to rely on whatever ~Eq~ instances the arguments to Identity
  (~a~ in the datatype declaration and ~v~ in the instance definition) has already.
  However the code will throw an error complaining about having no instance for ~(Eq a)~
  arising from a use of '=='.
+ Both ~v~ and ~v'~ are both of type ~a~ but we don't know anything about it
+ We can fix it with the same typeclass constraint syntax used with functions like so

#+BEGIN_SRC haskell
instance Eq a => Eq (Identity a) where
  (==) (Identity v) (Identity v') = v == v
#+END_SRC

+ This should work because we now know ~a~ has to have an instance of ~Eq~
+ Also Haskell will ensure that we don't check equality with values that don't
  have an ~Eq~ instance

#+BEGIN_SRC haskell
class Num a where
(+) :: a -> a -> a
(*) :: a -> a -> a
(-) :: a -> a -> a
negate :: a -> a
abs :: a -> a
signum :: a -> a
fromInteger :: Integer -> a

instance Num Integer
instance Num Int
instance Num Float
instance Num Double
#+END_SRC

+ This is the typeclass ~Num~ and some of its instances and functions

#+BEGIN_SRC haskell
class (Real a, Enum a) => Integral a where
  quot :: a -> a -> a
  rem :: a -> a -> a
  div :: a -> a -> a
  mod :: a -> a -> a
  quotRem :: a -> a -> (a, a)
  divMod :: a -> a -> (a, a)
  toInteger :: a -> Integer
#+END_SRC

+ This is the typeclass ~Integral~
+ The typeclass constraint ~(Real a, Enum a)~ means that any type that implements
  ~Integral~ must have instances of those two. So an integral type must be both
  a real number and enumerable and can therefore employ the methods of those typeclasses
+ In turn, the ~Real~ typeclass requires an instance of ~Num~, so the ~Integral~ class
  may put the methods of ~Real~ and ~Num~ into effect.
+ ~Real~ can't override the methods of ~Num~

#+BEGIN_SRC haskell
class (Num a) => Fractional a where
  (/) :: a -> a -> a
  recip :: a -> a
  fromRational :: Rational -> a
#+END_SRC

+ This is the ~Fractional~ typeclass, and its type argument ~a~
  also an instance of ~Num~, this is another example of typeclass inheritance
+ ~Fractional~ applies to fewer numbers than ~Num~ does
+ Instances of ~Fractional~ can use the functions defined in ~Num~
  but not all ~Num~ can use ~Fractional~ functions
  + Since nothing in ~Num~'s definition requires an instance of ~Fractional~
+ Consider this function ~divideThenAdd x y = (x / y) + 1~
  + If you give it the type signature ~Num a => a -> a -> a~ you'll get a type error
    + Because it could not deduce ~(Fractional a)~ from the use of '/' from the context
      of ~(Num a)~
  + You could fix it with this ~Fractional a => a -> a -> a~ because the '/' operator
    is an instance of ~Fractional~ only
+ The function could have been written like ~f \:: (Num a, Fractional a) => a -> a -> a~
  which is also correct, but I assume it is redundant since ~Fractional~ is already an
  instance of, and inherits from ~Num~

+ When you have a typeclass-constrained polymorphic value and need to evaluate it,
  the polymorphism must resolve to a specific concrete type
+ The concrete type must have an instance for all the required instances
  + i.e. if it is required to implement ~Num~ and ~Fractional~ then the concrete
    type can't be an ~Int~

#+BEGIN_SRC haskell
default Num Integer
default Real Integer
default Enum Integer
default Integral Integer
default Fractional Double
default RealFrac Double
default Floating Double
default RealFloat Double
#+END_SRC

+ The Haskell Report specifies these defaults relevant to numerical
  computations
+ These three operators are instances of ~Num~

#+BEGIN_SRC haskell
(+), (*), (-) :: Num a => a -> a -> a
#+END_SRC

+ This is a trimmed down version of ~:info Ord~

#+BEGIN_SRC haskell
class Eq a => Ord a where
  compare :: a -> a -> Ordering
  (<) :: a -> a -> Bool
  (>=) :: a -> a -> Bool
  (>) :: a -> a -> Bool
  (<=) :: a -> a -> Bool
  max :: a -> a -> a
  min :: a -> a -> a
instance Ord a => Ord (Maybe a)
instance (Ord a, Ord b) => Ord (Either a b)
instance Ord Integer
instance Ord a => Ord [a]
instance Ord Ordering
instance Ord Int
instance Ord Float
instance Ord Double
instance Ord Char
instance Ord Bool
#+END_SRC

+ As you can see, ~Ord~ is constrained by ~Eq~, or rather it inherits from said class
+ ~Ord~ requires ~Eq~ and its methods to compare items in a list and put them in order
+ Some of them gives a result of ~Bool~

#+BEGIN_SRC haskell
Prelude> compare 7 8
LT
Prelude> compare 4 (-4)
GT
Prelude> compare 4 4
EQ
Prelude> compare "Julie" "Chris"
GT
Prelude> compare True False
GT
Prelude> compare True True
EQ
#+END_SRC

+ This is the ~compare~ function which gives one of three outputs of type ~Ordering~
  1. GT
  2. LT
  3. EQ
     + I think it's obvious what they mean
+ The function works for any of the types listed above that implement ~Ord~
  + including ~Bool~
+ ~True~ is greater than ~False~ because of how the ~Bool~ datatype is defined:
  ~False | True~
+ The ~max~ and ~min~ functions output which ever is the greater or lesser
  of two given values respectively

#+BEGIN_SRC haskell
Prelude> max 7 8
8
Prelude> min 10 (-10)
-10
Prelude> max (3, 4) (2, 3)
(3,4)
Prelude> min [2, 3, 4, 5] [3, 4, 5, 6]
[2,3,4,5]
Prelude> max "Julie" "Chris"
"Julie"
#+END_SRC

+ If you try to enter ~max "Julie"~ you'll get an error along the lines of this

#+BEGIN_SRC haskell
No instance for (Show ([Char] -> [Char]))
arising from a use of ‘print’
#+END_SRC
+ The typeclass it couldn't find an instance for was ~Show~
+ It couldn't find an instance of ~Show~ for the type ~[Char] -> [Char]~
  + "Nothing with type (->) should have a ~Show~ instance as a general rule because
    (->) denotes a function rather than a constant value"
+ We wanted an instance of ~Show~ because ~print~ was indirectly invoked, which has a
  type of ~Show a => a -> IO ()~
  + GHCi always indirectly invokes ~print~ when we try to input and evaluate an
    expression
+ The error message is because ~max~ applied to a single String argument needs another
  before it returns a String value that is printable

+ When you derive ~Ord~ instances for a datatype, they rely on how the datatype is
  defined, but when you write your own instances, you can define the behavior yourself
+ Using this example again to demonstrate

#+BEGIN_SRC haskell
data DayOfWeek =
  Mon | Tue | Weds | Thu | Fri | Sat | Sun
  deriving (Ord, Show)
#+END_SRC

+ We derived ~(Ord, Show)~ this time because we should still have the ~Eq~ instance
  we wrote earlier in scope
  + alternatively you can just derive ~Eq~
+ You can't have an ~Ord~ instance without also having an ~Eq~ instance
+ If you enter ~Mon > Tue~ in GHCi it will evaluate to ~False~ because ~Mon~ preceeds
  ~Tue~
+ At the same time ~Sun > Mon~ is true because it the former suceeds the latter
+ You can also do something like ~compare Tue Weds~ which evaluates to ~LT~
+ You can override the ordering of the constructors

#+BEGIN_SRC haskell
data DayOfWeek =
  Mon | Tue | Weds | Thu | Fri | Sat | Sun
  deriving (Eq, Show)

instance Ord DayOfWeek where
  compare Fri Fri = EQ
  compare Fri _   = GT
  compare _ Fri   = LT
  compare _ _     = EQ
#+END_SRC

+ In this instance, the ordering is manually overridden so that friday is always their
  greatest day of the week
+ At the same time, comparing two days other than friday will always evaluate to ~EQ~
+ Since we also derived ~Eq~ we also get to use the function operators belonging to it
  + ~Sat == Mon = False~
  + ~Fri == Fri = True~
+ As a rule of thumb, it is wise to ensure that ~Ord~ instances "agree" with your ~Eq~
  instances, whether they (~Eq~) are derived or manually written
  + If ~x == y~ then ~compare x y~ should return ~EQ~
  + Also you want your ~Ord~ instances to define a sensible total order
    + You ensure this in part by covering all cases and not writing partial
      instances

+ The following won't typecheck because we lack ~Eq~

#+BEGIN_SRC haskell
check' :: a -> a -> Bool
check a a' = a == a'
#+END_SRC

+ However using ~Ord~ instead of ~Eq~ also works

#+BEGIN_SRC haskell
check' :: Ord a => a -> a -> Bool
check a a' = a == a'
#+END_SRC

+ It works because anything that provides an instance of ~Ord~ /must/ by definition
  already have an instance of ~Eq~
+ We know this because ~Ord~ inherits from ~Eq~
+ If you type ~:info Ord~ you get ~class Eq => a Ord a where~ as the first line
  + In English, this means that any ~a~ which wants to define an ~Ord~ instance must
    already provide an ~Eq~ instance
    + So in a sense, ~Eq~ is a superclass of ~Ord~

+ The ~Enum~ typeclass covers types that are enumerable, there having known predecessors
  and successors.
+ This is info on the typeclass

#+BEGIN_SRC haskell
Prelude> :info Enum
class Enum a where
  succ :: a -> a
  pred :: a -> a
  toEnum :: Int -> a
  fromEnum :: a -> Int
  enumFrom :: a -> [a]
  enumFromThen :: a -> a -> [a]
  enumFromTo :: a -> a -> [a]
  enumFromThenTo :: a -> a -> a -> [a]

instance Enum Ordering
instance Enum Integer
instance Enum Int
instance Enum Char
instance Enum Bool
instance Enum ()
instance Enum Float
instance Enum Double
#+END_SRC

+ Numbers and characters obviously have successors and predecessors
+ You have ~succ~ and ~pred~ functions that get the successor and predecessor
  respectively of a value

#+BEGIN_SRC haskell
succ 4 -- 5
pred 4 -- 3

succ 'b' -- 'c'
pred 'b' -- 'a'
#+END_SRC

+ There's also ~enumFromTo~ which constructs a range from a starting and end value of
  identical concrete types

#+BEGIN_SRC haskell
enumFromTo 3 8
[3,4,5,6,7,8]

enumFromTo 'a' 'f'
"abcdef"
#+END_SRC

+ And then there's ~enumFromThenTo~

#+BEGIN_SRC haskell
enumFromThenTo 1 10 100
[1,10,19,28,37,46,55,64,73,82,91,100]
#+END_SRC

+ I assume it increments by 9 since that's the range of numbers before 10

+ ~Show~ is a typeclass for the creation of human-readable string representations
  of structured data
+ GHCi uses it to create string values it can print in the terminal
+ ~Show~ is not a serialization format
  + Serialization is how data is rendered to a textual or binary format for persistence
    or communicating with other computers over a network
    + An example of this is saving data to a file on disk
+ This is the (shortened) info of ~Show~

#+BEGIN_SRC haskell
class Show a where
  showsPrec :: Int -> a -> ShowS
  show :: a -> String
  showList :: [a] -> ShowS

instance Show a => Show [a]
instance Show Ordering
instance Show a => Show (Maybe a)
instance Show Integer
instance Show Int
instance Show Char
instance Show Bool
instance Show ()
instance Show Float
instance Show Double
#+END_SRC

+ Various number types, boolean values, tuples, and characters are already
  instances of ~Show~
+ Which means they already have a defined ability to be printed on the screen
+ There is also the function ~show~ (mind the capitalization) which takes a polymorphic
  value and returns it as ~String~

+ ~print~ is defined in the Prelude as a function to output a value
  of any printable (as in, instance of ~Show~) type to the screen or any other
  output device
+ The type of ~print~ is ~:: Show a => a -> IO ()~
+ It takes an constrained polymorphic type ~a~ that is an stance of ~Show~
  and returns an ~IO ()~ result
+ ~IO ()~ is the obligatory type of the ~main~ function in any haskell source code file
  + This is because the ~main~ function /only/ produces side effects
+ An I/O action is an action that has side effects, including reading from input
  and printing something to the screen that will contain a return value
+ The () denotes an empty tuple, also known as a /unit/
+ An IO action, like any other expression in Haskell must return something, it can't
  return a /nothing/
+ So a unit is used to represent the return value at the end of an I/O action
  + As in, the ~print~ function will first do the I/O action of printing the value
    to the terminal and then complete the action, marking an end to the running of the
    function and a delimitation of side effects by returning a unit
    + It does not print the empty tuple but it is implicitly there
+ The simplest way to differentiate between a value with a typical like such as ~String~
  and the same type with ~IO~ (as in, ~IO String~) is that I/O actions are formulas
+ ~IO String~ is more of a "means of producing" a String, why may require performing
  side effects along the way until we get a ~String~ value
+ This is a ~String~ value: ~myVal \:: String~
+ And this is a "means of obtaining a value" by performing effects or IO of ~String~:
  ~ioString \:: IO String~
+ An IO action is performed when we call ~main~, but we also perform an IO action when
  use the ~print~ function, explicitly or implicitly (such as in the GHCi)

+ A minimal implementation of an instance of ~Show~ only requires that ~show~ and
  ~showsPrec~ is implemented

#+BEGIN_SRC haskell
data Mood = Blah

instance Show Mood where
  show _ = "Blah"
------GHCI---------
Prelude > Blah
Blah
#+END_SRC

+ When you try to define a datatype and invoke it in GHCi without a ~Show~ instance,
  you get an error complaining about having no instance for ~Show~ on the datatype
  arising from the use of ~print~
+ You can /derive/ an instance for ~Show~ on the data declaration since GHC supports
  deriving instances for ~Show~
  + ~data Mood = Blah deriving Show~
    + This works exactly like the code block above

* Exercises
** Page 272
    1.
#+BEGIN_SRC haskell
data TisAnInteger =
  TisAn Integer

instance Eq TisAnInteger where
  (==) (TisAn x) (TisAn y) = x == y
#+END_SRC

    2.
#+BEGIN_SRC haskell
data TwoIntegers =
  Two Integer Integer

instance Eq TwoIntegers where
  (==) (Two x y) (Two x' y') = x == x' && y == y'
#+END_SRC

    3.
#+BEGIN_SRC haskell
data StringOrInt = TisAnInt Int
                 | TisAString String

instance Eq StringOrInt where
 (==) (TisAnInt x) (TisAnInt y) = x == y
 (==) (TisAString a) (TisAString b) a == b
 (==) __ = False
#+END_SRC

    4.
#+BEGIN_SRC haskell
data Pair a =
  Pair a a

instance Eq a => Eq (Pair a) where
  (==) (Pair x x') (Pair y y') = x == y && y == y'
#+END_SRC

    5.
#+BEGIN_SRC haskell
data Tuple a b =
  Tuple a b

instance (Eq a, Eq b) => Eq (Tuple a b) where
  (==) (Tuple x y) (Tuple x' y') = x == x' && y == y'
#+END_SRC

    6.
#+BEGIN_SRC haskell
data Which a = ThisOne a
             | ThatOne a

instance (Eq a) => Eq (Which a) where
  (==) (ThisOne x) (ThisOne x') = x == x'
  (==) (ThatOne y) (ThatOne y') = y == y'
  (==) __ = False
#+END_SRC

    7.
#+BEGIN_SRC haskell
data EitherOr a b = Hello a
                  | Goodbye b

instance (Eq a, Eq b) => Eq (EitherOr a b) where
  (==) (Hello x) (Hello x') = x == y'
  (==) (Goodbye x) (Goodbye x') = x == y'
  (==) __ = False
#+END_SRC
** Page 275
   #+BEGIN_SRC haskell
quotRem, divMod :: Integral a => a -> a -> (a, a)
   #+END_SRC
   ~quotRem~ takes two numbers and returns a tuple containing the result
   of the integer divison, and remainder

   ~divMod~ is the same as ~quotRem~ but returns the modulo instead of remainder
** Page 294
    1. ~max (length [1,2,3]) (length [8,9,10,11,12])~ returns 5 which is the length
       of the second argument, the output is of type ~Int~ which is also an instance of
       ~Ord~ and ~max :: Ord a => a -> a -> a~
    2. ~compare (3 * 4) (3 * 5)~ returns ~LT~ because the first argument evaluates to
       12 which is less than the evaluation of the second argument which is 15
    3. ~compare "Julie" True~ does not work because it is comparing two arguments of
       different types, namely ~String~ and ~Bool~ respectively
    4. ~(5 + 3) > (3 + 6)~ evaluates to False because 8 is less than 9
